apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: migration-toolkit-location
  description: Links to additional entities in the migration-toolkit repository.
  annotations:
    github.com/project-slug: Bandwidth/migration-toolkit
spec:
  targets:
    - ./component.yaml
    # - add more components using relative filepaths here
    # - you may also rename/move the original component.yaml file
